---
- name: Install maven 
  hosts: db
  become: yes

  tasks:
  - name: Ensure maven service is present
    apt: 
      name: maven
      state: latest
  
  - name: Clone a github repository
    git:
      repo: https://github.com/odiora/simple-jar-app
      dest: /home/git/
      clone: yes
      update: yes

  - name: Build application
    shell:
      cmd: mvn package 
      chdir: /home/git/

  - name: Copy application to runner host
    synchronize: src={{item}} dest=/tmp/ mode=pull
    with_items:
      - "/home/git"

- name: Install Java
  hosts: web
  become: yes

  tasks:
  - name: Ensure java service is present
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Ensure application to runner
    copy: 
      src: /tmp/git 
      dest: /home/

  - name: application run
    shell:
      cmd: java -jar simple-jar-app-0.0.1-SNAPSHOT.jar
      chdir: /home/git/target/
---