---
# tasks file for maven
- name: install packages
  apt: name={{ package }} state=present

- name: Clone a github repository
  git:
    repo: https://github.com/odiora/simple-jar-app
    dest: "{{ path }}"
    clone: yes
    update: yes

- name: Build application
  shell:
    cmd: mvn package 
    chdir: "{{ path }}"



